name: Check Power Status

on:
  # Run the script every 15 minutes
  schedule:
    - cron: '*/10 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run power check script
        run: python electricity_detector.py

      - name: Commit and push status changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add elec_status.txt
          # Only commit and push if there are changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update power status"; git push)
